// File generated by FlutterFire CLI.
// Platforms without options throw, and Strata skips Firebase there so the app
// still boots on local repositories.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(_notConfigured('macos'));
      case TargetPlatform.windows:
        throw UnsupportedError(_notConfigured('windows'));
      case TargetPlatform.linux:
        throw UnsupportedError(_notConfigured('linux'));
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static String _notConfigured(String platform) =>
      'DefaultFirebaseOptions have not been configured for $platform — '
      'run FlutterFire CLI from dino_app/ (see docs/iteration-8-firestore-roadmap.md).';

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCyh-CS59hIB-nIi8f7ludafrYNCsq6a4',
    appId: '1:648719646108:web:24814c500020f353669c59',
    messagingSenderId: '648719646108',
    projectId: 'dino-app-90aa2',
    authDomain: 'dino-app-90aa2.firebaseapp.com',
    storageBucket: 'dino-app-90aa2.firebasestorage.app',
    measurementId: 'G-V814M75QKF',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBC66zwXvl3Cy1X-cHtVsN_L4hlM-WBacI',
    appId: '1:648719646108:ios:ac89295964845b81669c59',
    messagingSenderId: '648719646108',
    projectId: 'dino-app-90aa2',
    storageBucket: 'dino-app-90aa2.firebasestorage.app',
    iosBundleId: 'com.example.dinoApp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJ4RbaUZJbYqR30DKhVf-zdApO4eaEbXc',
    appId: '1:648719646108:android:1578f75aa373aa07669c59',
    messagingSenderId: '648719646108',
    projectId: 'dino-app-90aa2',
    storageBucket: 'dino-app-90aa2.firebasestorage.app',
  );
}
