// File generated by FlutterFire CLI.
// Until `flutterfire configure` is run, [currentPlatform] throws and
// Strata skips Firebase so the app still boots on local repositories.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(_notConfigured('web'));
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(_notConfigured('android'));
      case TargetPlatform.iOS:
        throw UnsupportedError(_notConfigured('ios'));
      case TargetPlatform.macOS:
        throw UnsupportedError(_notConfigured('macos'));
      case TargetPlatform.windows:
        throw UnsupportedError(_notConfigured('windows'));
      case TargetPlatform.linux:
        throw UnsupportedError(_notConfigured('linux'));
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static String _notConfigured(String platform) =>
      'DefaultFirebaseOptions have not been configured for $platform — '
      'run FlutterFire CLI from dino_app/ (see docs/iteration-8-firestore-roadmap.md).';
}
